# cat newvm.yml
---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: "vcenter_hostname"
      prompt: "Rentre le nom/IP du Vcenter?"
      private: no
    - name: "vcenter_username"
      prompt: "Rentre le login du vcenter"
      private: no
    - name: "vcenter_password"
      prompt: "Rentre le mdp du login vcenter"
      private: yes
    - name: "esxi_hostname"
      prompt: "Choisis l'esxi que tu veux"
      private: no
    - name: "guest"
      prompt: "Choisis le nom de la VM"
      private: no
    - name: "disk"
      prompt: "Choisis le capacité du disque que tu souhaite"
      private: no
    - name: "memory"
      prompt: "Choisis le nombre de RAM"
      private: no
    - name: "cpu"
      prompt: "Choisis le nombre de CPU "
      private: no 

  tasks:
  - vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      guest: "{{ guest }}"
      state: powered_on
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
      vm_disk:
        disk1:
          size_gb: "{{ disk }}"
          type: thin
          datastore: Datastore_ISCSI
          folder: Machine virtuelle Active
      vm_nic:
        nic1:
          type: vmxnet3
          network: Serveur VLAN 500
          network_type: standard
      vm_hardware:
        memory_mb: "{{ memory }}"
        num_cpus: "{{ cpu }}"
        osid: centos64Guest
        scsi: paravirtual
        vm_cdrom:
          type: "iso"
          iso_path: "Datastore Local_ISO/ISO/04_CENTOS/CentOS-7-x86_64-DVD-1810.iso"
      esxi:
        datacenter: Siege
        hostname: "{{ esxi_hostname }}"
      validate_certs: False